use std::fmt;

use error::message::ErrorMessage;

/// An error struct generated by AST conversion.
pub struct ASTError {
    /// ErrorMessage
    pub message: ErrorMessage,
    /// `format!`'ed representation of relevant `ParseNode`
    pub node: String,
}

impl ASTError {
    /// Constructs a WeederError from an ErrorMessage and a `format!`able node.
    pub fn new<T>(message: ErrorMessage, node: &T) -> ASTError
        where T: fmt::Display
    {
        ASTError {
            message: message,
            node: format!("{}", node),
        }
    }
}

impl fmt::Display for ASTError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "error: {}\n\n{}", self.message, self.node)
    }
}
