use std::str::FromStr;

#[derive(Debug,Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: Option<String>,
}

#[derive(Debug,Clone,PartialEq)]
pub enum TokenKind {
    Assignment,
    Equality,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Not,
    NotEqual,

    LBrace,
    RBrace,
    LBracket,
    RBracket,
    LParen,
    RParen,

    Dot,
    FSlash,
    Minus,
    Percent,
    Plus,
    Star,

    And,
    Or,
    BitAnd,
    BitOr,
    BitXor,

    Import,
    Package,

    Private,
    Protected,
    Public,

    Abstract,
    Extends,
    Implements,
    Interface,
    Final,
    Native,
    Static,

    Boolean,
    Byte,
    Char,
    Int,
    Short,
    Str,
    Void,

    False,
    True,
    Null,

    Cloneable,
    Integer,
    Number,
    Object,

    Class,
    Delete,
    Instanceof,
    New,
    This,

    Else,
    For,
    If,
    Return,
    While,

    Identifier,
    CharValue,
    NumValue,
    StrValue,

    Comma,
    Semicolon,

    BOF,
    EOF,

    // INVALID
    AssignmentAddition,
    AssignmentAnd,
    AssignmentDivision,
    AssignmentLShift,
    AssignmentModulus,
    AssignmentMultiplication,
    AssignmentOr,
    AssignmentRRShift,
    AssignmentRShift,
    AssignmentSubtraction,
    AssignmentXor,
    Break,
    Case,
    Catch,
    Colon,
    Complement,
    Continue,
    Decrement,
    Default,
    Do,
    Double,
    Finally,
    Float,
    Goto,
    Increment,
    Long,
    LShift,
    Question,
    RRShift,
    RShift,
    Strictfp,
    Super,
    Switch,
    Synchronized,
    Throw,
    Throws,
    Transient,
    Try,
    Volatile,

    // Parsing
    NonTerminal,
}

impl FromStr for TokenKind {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "!" => Ok(TokenKind::Not),
            "!=" => Ok(TokenKind::NotEqual),
            "%" => Ok(TokenKind::Percent),
            "%=" => Ok(TokenKind::AssignmentModulus),
            "&" => Ok(TokenKind::BitAnd),
            "&&" => Ok(TokenKind::And),
            "&=" => Ok(TokenKind::AssignmentAnd),
            "(" => Ok(TokenKind::LParen),
            ")" => Ok(TokenKind::RParen),
            "*" => Ok(TokenKind::Star),
            "*=" => Ok(TokenKind::AssignmentMultiplication),
            "+" => Ok(TokenKind::Plus),
            "++" => Ok(TokenKind::Increment),
            "+=" => Ok(TokenKind::AssignmentAddition),
            "-" => Ok(TokenKind::Minus),
            "--" => Ok(TokenKind::Decrement),
            "-=" => Ok(TokenKind::AssignmentSubtraction),
            "/" => Ok(TokenKind::FSlash),
            "/=" => Ok(TokenKind::AssignmentDivision),
            "<" => Ok(TokenKind::LessThan),
            "<<" => Ok(TokenKind::LShift),
            "<<=" => Ok(TokenKind::AssignmentLShift),
            "<=" => Ok(TokenKind::LessThanOrEqual),
            "=" => Ok(TokenKind::Assignment),
            "==" => Ok(TokenKind::Equality),
            ">" => Ok(TokenKind::GreaterThan),
            ">=" => Ok(TokenKind::GreaterThanOrEqual),
            ">>" => Ok(TokenKind::RShift),
            ">>=" => Ok(TokenKind::AssignmentRShift),
            ">>>" => Ok(TokenKind::RRShift),
            ">>>=" => Ok(TokenKind::AssignmentRRShift),
            "?" => Ok(TokenKind::Question),
            "[" => Ok(TokenKind::LBracket),
            "]" => Ok(TokenKind::RBracket),
            "^" => Ok(TokenKind::BitXor),
            "^=" => Ok(TokenKind::AssignmentXor),
            "ABSTRACT" => Ok(TokenKind::Abstract),
            "BOF" => Ok(TokenKind::BOF),
            "BOOLEAN" => Ok(TokenKind::Boolean),
            "BREAK" => Ok(TokenKind::Break),
            "BYTE" => Ok(TokenKind::Byte),
            "CASE" => Ok(TokenKind::Case),
            "CATCH" => Ok(TokenKind::Catch),
            "CHAR" => Ok(TokenKind::Char),
            "CharacterLit" => Ok(TokenKind::CharValue),
            "CLASS" => Ok(TokenKind::Class),
            "CLONEABLE" => Ok(TokenKind::Cloneable),
            "COLON" => Ok(TokenKind::Colon),
            "COMMA" => Ok(TokenKind::Comma),
            "CONTINUE" => Ok(TokenKind::Continue),
            "DEFAULT" => Ok(TokenKind::Default),
            "DELETE" => Ok(TokenKind::Delete),
            "DO" => Ok(TokenKind::Do),
            "DOT" => Ok(TokenKind::Dot),
            "DOUBLE" => Ok(TokenKind::Double),
            "ELSE" => Ok(TokenKind::Else),
            "EOF" => Ok(TokenKind::EOF),
            "EXTENDS" => Ok(TokenKind::Extends),
            "FALSE" => Ok(TokenKind::False),
            "FINAL" => Ok(TokenKind::Final),
            "FINALLY" => Ok(TokenKind::Finally),
            "FLOAT" => Ok(TokenKind::Float),
            "FOR" => Ok(TokenKind::For),
            "GOTO" => Ok(TokenKind::Goto),
            "IDENTIFIER" => Ok(TokenKind::Identifier),
            "IF" => Ok(TokenKind::If),
            "IMPLEMENTS" => Ok(TokenKind::Implements),
            "IMPORT" => Ok(TokenKind::Import),
            "INSTANCEOF" => Ok(TokenKind::Instanceof),
            "INT" => Ok(TokenKind::Int),
            "IntegerLit" => Ok(TokenKind::NumValue),
            "INTEGER" => Ok(TokenKind::Integer),
            "INTERFACE" => Ok(TokenKind::Interface),
            "LONG" => Ok(TokenKind::Long),
            "NATIVE" => Ok(TokenKind::Native),
            "NEW" => Ok(TokenKind::New),
            "NullLit" => Ok(TokenKind::Null),
            "NUMBER" => Ok(TokenKind::Number),
            "OBJECT" => Ok(TokenKind::Object),
            "PACKAGE" => Ok(TokenKind::Package),
            "PRIVATE" => Ok(TokenKind::Private),
            "PROTECTED" => Ok(TokenKind::Protected),
            "PUBLIC" => Ok(TokenKind::Public),
            "RETURN" => Ok(TokenKind::Return),
            "SEMICOLON" => Ok(TokenKind::Semicolon),
            "SHORT" => Ok(TokenKind::Short),
            "STATIC" => Ok(TokenKind::Static),
            "STRICTFP" => Ok(TokenKind::Strictfp),
            "STRING" => Ok(TokenKind::Str),
            "StringLit" => Ok(TokenKind::StrValue),
            "SUPER" => Ok(TokenKind::Super),
            "SWITCH" => Ok(TokenKind::Switch),
            "SYNCHRONIZED" => Ok(TokenKind::Synchronized),
            "THIS" => Ok(TokenKind::This),
            "THROW" => Ok(TokenKind::Throw),
            "THROWS" => Ok(TokenKind::Throws),
            "TRANSIENT" => Ok(TokenKind::Transient),
            "TRUE" => Ok(TokenKind::True),
            "TRY" => Ok(TokenKind::Try),
            "VOID" => Ok(TokenKind::Void),
            "VOLATILE" => Ok(TokenKind::Volatile),
            "WHILE" => Ok(TokenKind::While),
            "{" => Ok(TokenKind::LBrace),
            "|" => Ok(TokenKind::BitOr),
            "|=" => Ok(TokenKind::AssignmentOr),
            "||" => Ok(TokenKind::Or),
            "}" => Ok(TokenKind::RBrace),
            "~" => Ok(TokenKind::Complement),

            _ => Ok(TokenKind::NonTerminal),
        }
    }
}
